export interface Post {
  id: string;
  content: string;
  hashtags: string[];
  post_type: string;
  best_time_to_post: string;
  expected_reach: string;
}

export interface TrustBreakdown {
  total: number;
  github_component: number;
  linkedin_component: number;
  checks: {
    is_original_work: boolean;
    solo_or_lead_author: boolean;
    has_commit_history: boolean;
    readme_quality: boolean;
    linkedin_profile_real: boolean;
  };
  warnings: string[];
}

export interface GithubProfile {
  repo_name: string;
  description: string;
  language: string;
  stars: number;
  contributors: number;
  commits: number;
  is_fork: boolean;
  url: string;
}

export interface LinkedinProfile {
  name: string;
  headline: string;
  location: string;
  connection_count: number;
  profile_exists: boolean;
}

export interface RecruiterScores {
  technical_post: number;
  story_post: number;
  announcement_post: number;
  reasoning: string;
}

export interface ImageCardData {
  html: string;
  data: {
    title: string;
    description: string;
    tech_stack: string[];
    author_name: string;
    author_role: string;
    language: string;
    stars: number;
    trust_badge: string;
    trust_score: number;
    github_url: string;
  };
}

export interface AnalyzeSuccess {
  status: "success";
  /** Present when generated by the Python backend */
  tech_stack_flat?: string[];
  trust: {
    score: number;
    level: "HIGH" | "MEDIUM" | "LOW";
    badge: "VERIFIED" | "STANDARD";
    breakdown: TrustBreakdown;
  };
  profile: {
    github: GithubProfile;
    linkedin: LinkedinProfile;
  };
  tech_stack: Record<string, string[]>;
  posts: {
    technical: Post;
    story: Post;
    announcement: Post;
  };
  recruiter_scores: RecruiterScores;
  image_card: ImageCardData;
  generated_at: string;
}

export interface AnalyzeRejected {
  status: "rejected";
  trust_score?: number;
  score_breakdown?: TrustBreakdown;
  rejection_reason: string;
  repo_meta?: Record<string, unknown>;
  linkedin_profile?: LinkedinProfile;
}

export type AnalyzeResponse = AnalyzeSuccess | AnalyzeRejected;

export function isAnalyzeSuccess(r: unknown): r is AnalyzeSuccess {
  return (
    typeof r === "object" &&
    r !== null &&
    "status" in r &&
    (r as { status: unknown }).status === "success"
  );
}
